# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/slsa-framework/slsa-verifier
%global goipath         github.com/slsa-framework/slsa-verifier
Version:                2.7.1

%gometa -L -f


Name:           slsa-verifier
Release:        %autorelease
Summary:        Verify provenance from SLSA compliant builders

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
Verify provenance from SLSA compliant builders.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
build_date=$(date -u '+%%Y-%%m-%%d')
export GO_LDFLAGS="-X sigs.k8s.io/release-utils/version.gitVersion=%{version}"
GO_LDFLAGS+=" -X sigs.k8s.io/release-utils/version.buildDate=${build_date}"
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/slsa-verifier %{goipath}/v2/cli/slsa-verifier

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%gocheck -d verifiers/internal/gcb/slsaprovenance/v1.0 -d verifiers/internal/gha

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs README.md RELEASE.md SECURITY.md SHA256SUM.md requirements-lint.txt
%{_bindir}/slsa-verifier


%changelog
%autochangelog
